
// Mapping of subcategories to their parent category routes
export const subcategoryToCategoryMapping: Record<string, string> = {
  // Camisas e Uniformes - CAMISAS
  'Body Infantil': '/camisas-uniformes',
  'Body Infantil Colorido': '/camisas-uniformes',
  'Camisa Polo Feminina': '/camisas-uniformes',
  'Camisa Polo Feminina Dry': '/camisas-uniformes',
  'Camisa Polo Masculina': '/camisas-uniformes',
  'Camisa Polo Masculina Dry': '/camisas-uniformes',
  'Feminina Algodão': '/camisas-uniformes',
  'Feminina Algodão Colorida': '/camisas-uniformes',
  'Feminina Branca': '/camisas-uniformes',
  'Feminina Colorida': '/camisas-uniformes',
  'Feminina Raglan': '/camisas-uniformes',
  'Infantil Branca': '/camisas-uniformes',
  'Infantil Colorida': '/camisas-uniformes',
  'Masculina Branca': '/camisas-uniformes',
  'Masculina Algodão': '/camisas-uniformes',
  'Masculina Algodão Colorida': '/camisas-uniformes',
  'Masculina Colorida': '/camisas-uniformes',
  'Masculina Reglan': '/camisas-uniformes',
  'Regata Feminina Branca': '/camisas-uniformes',
  'Regata Feminina Colorida': '/camisas-uniformes',
  'Regata Masculina Branca': '/camisas-uniformes',
  'Regata Masculina Colorida': '/camisas-uniformes',

  // Camisas e Uniformes - UNIFORMES
  'Avental Napo': '/camisas-uniformes',
  'Avental Oxford': '/camisas-uniformes',
  'Bermuda de Brim': '/camisas-uniformes',
  'Bota Cano Alto': '/camisas-uniformes',
  'Bota Cano Curto': '/camisas-uniformes',
  'Calça Carijó': '/camisas-uniformes',
  'Calça Brim': '/camisas-uniformes',
  'Colete Futebol': '/camisas-uniformes',
  'Jaleco de Brim': '/camisas-uniformes',
  'Jaleco de Enfermagem': '/camisas-uniformes',

  // Papelaria
  'ADESIVO 30 FOLHAS': '/papelaria',
  'FOTOGRÁFICO A4 20 FOLHAS': '/papelaria',
  'FOTOGRÁFICO A4 50 FOLHAS': '/papelaria',
  'FOTOGRÁFICO A4 ESPECIAL': '/papelaria',
  'PAPEL OBM': '/papelaria',
  'SUBLIMÁTICO A3': '/papelaria',
  'SUBLIMÁTICO A4': '/papelaria',
  'VINIL': '/papelaria',

  // Equipamentos - MÁQUINAS
  'CAMEO SILHOUETTE': '/equipamentos',
  'DIAMOND 360º TRANSFER': '/equipamentos',
  'IMPRESSORA EPSON': '/equipamentos',
  'PLOTTER DE RECORTE': '/equipamentos',
  'PRENSA 8 EM 1': '/equipamentos',
  'PRENSA CILINDRICA': '/equipamentos',
  'PRENSA LONG DRINK': '/equipamentos',
  'PRENSA PLANA': '/equipamentos',
  'PRENSA PORTÁTIL': '/equipamentos',

  // Equipamentos - KIT EMPREENDEDOR
  'KIT CILÍNDRICO': '/equipamentos',
  'KIT PLANO': '/equipamentos',

  // Canecas
  'CANECA AÇO INOX': '/canecas',
  'CANECA ALUMÍNIO': '/canecas',
  'CANECA BELLY': '/canecas',
  'CANECA BRANCA': '/canecas',
  'CANECA BASE GLITTER': '/canecas',
  'CANECA BOLINHA': '/canecas',
  'CANECA CHOPP': '/canecas',
  'CANECA COM COLHER': '/canecas',
  'CANECA COM GLITTER': '/canecas',
  'CANECA CÔNICA': '/canecas',
  'CANECA CORAÇÃO': '/canecas',
  'CANECA CROMADA': '/canecas',
  'CANECA FALL': '/canecas',
  'CANECA INOX': '/canecas',
  'CANECA JATEADA': '/canecas',
  'CANECA MÁGICA': '/canecas',
  'CANECA MAZON': '/canecas',
  'CANECA NEON': '/canecas',
  'CANECA PEROLADA': '/canecas',
  'CANECA POLÍMERO': '/canecas',
  'CANECA DE TARJA SUBLIMÁTICA': '/canecas',
  'CANECA WHISKY': '/canecas',

  // Sublimação - SQUEEZES
  'ALUMÍNIO BIG MOUTH': '/sublimacao',
  'ALUMÍNIO LONG NECK': '/sublimacao',
  'BOLINHA': '/sublimacao',
  'COELHINHO': '/sublimacao',
  'COPO TÉRMICO': '/sublimacao',
  'CRAZY CAT': '/sublimacao',
  'CRAZY DOG': '/sublimacao',
  'GATINHO': '/sublimacao',
  'INOX COM GLITTER': '/sublimacao',
  'INOX COROA': '/sublimacao',
  'INOX TÉRMICA': '/sublimacao',
  'LATINHA INOX': '/sublimacao',
  'MOSQUETÃO': '/sublimacao',
  'NIKE': '/sublimacao',
  'POLÍMERO': '/sublimacao',
  'TAMPA BAMBU': '/sublimacao',
  'TÉRMICA CAFÉ': '/sublimacao',
  'TÉRMICA DIGITAL': '/sublimacao',

  // Sublimação - INSUMOS
  'ALMOCHAVEIRO': '/sublimacao',
  'AZULEJO': '/sublimacao',
  'BASE GIRATÓRIA': '/sublimacao',
  'BOLSA ECOBAG': '/sublimacao',
  'BONÉ DEKO': '/sublimacao',
  'BONÉ TACTEL': '/sublimacao',
  'CANETA': '/sublimacao',
  'CAPA DE ALMOFADA': '/sublimacao',
  'CAPA DE ALMOFADA LANTEJOULA': '/sublimacao',
  'CAVALETES': '/sublimacao',
  'CHAVEIRO ACRÍLICO': '/sublimacao',
  'CHAVEIRO POLÍMERO': '/sublimacao',
  'CHINELO': '/sublimacao',
  'COLOCADOR DE TIRAS CHINELO': '/sublimacao',
  'FITA TÉRMICA': '/sublimacao',
  'LAVABINHO': '/sublimacao',
  'LAVABO': '/sublimacao',
  'MANTA SILICONE': '/sublimacao',
  'MDF': '/sublimacao',
  'MDF TEMÁTICO': '/sublimacao',
  'MOTOR RELÓGIO': '/sublimacao',
  'MOUSE PAD': '/sublimacao',
  'PLACA ACRÍLICA': '/sublimacao',
  'QUEBRA CABEÇA': '/sublimacao',
  'RELÓGIO DE VIDRO': '/sublimacao',
  'RELÓGIO MDF': '/sublimacao',
  'SACOLA KRAFT': '/sublimacao',

  // Sublimação - SUPORTES
  'SUPORTES': '/sublimacao',

  // Sublimação - MÁQUINAS (already mapped above in equipamentos, but adding for completeness)
  // Sublimação - KIT EMPREENDEDOR
  'KIT CILINDRICO': '/sublimacao',

  // Serigrafia - INSUMOS
  'AUX PLÁSTICOS': '/serigrafia',
  'BARRICA CLEAR': '/serigrafia',
  'CLEAR FILM': '/serigrafia',
  'COBERCOLOR': '/serigrafia',
  'COLA PERMANENTE': '/serigrafia',
  'COLOR PAPEL': '/serigrafia',
  'COPO MEDIDOR': '/serigrafia',
  'CROMA': '/serigrafia',
  'EMULSÃO': '/serigrafia',
  'ESPÁTULA': '/serigrafia',
  'FOTO ESTAMPA': '/serigrafia',
  'GRAMPEADOR': '/serigrafia',
  'GRAMPO': '/serigrafia',
  'LUVA': '/serigrafia',
  'NYLON': '/serigrafia',
  'PARAFUSOS': '/serigrafia',

  // Serigrafia - TINTAS
  'HIDROCOLOR': '/serigrafia',
  'HIDROMIX': '/serigrafia',
  'PIGMENTO': '/serigrafia',

  // Serigrafia - MÁQUINAS
  'CILINDRICA SMART': '/serigrafia',
  'CILINDRICA TEX COM SUPORTE 2 BERCOS': '/serigrafia',
  'PLOTTER SEM SUPORTE': '/serigrafia',
};
